// languages-meta.js — реестр 72 языков БЕЗ самих словарей (только
// метаданные: имя, нативное имя, RTL). Сами словари грузятся лениво
// через js/lang/<code>.js — см. I18N.ensureLoaded() в i18n.js.
const LANGUAGES = {
  en: { name: "English", native: "English", rtl: false },
  ru: { name: "Russian", native: "Русский", rtl: false },
  es: { name: "Spanish", native: "Español", rtl: false },
  de: { name: "German", native: "Deutsch", rtl: false },
  fr: { name: "French", native: "Français", rtl: false },
  pt: { name: "Portuguese", native: "Português", rtl: false },
  it: { name: "Italian", native: "Italiano", rtl: false },
  tr: { name: "Turkish", native: "Türkçe", rtl: false },
  ar: { name: "Arabic", native: "العربية", rtl: true },
  hi: { name: "Hindi", native: "हिन्दी", rtl: false },
  zh: { name: "Chinese", native: "中文", rtl: false },
  ja: { name: "Japanese", native: "日本語", rtl: false },
  ko: { name: "Korean", native: "한국어", rtl: false },
  uk: { name: "Ukrainian", native: "Українська", rtl: false },
  vi: { name: "Vietnamese", native: "Tiếng Việt", rtl: false },
  pl: { name: "Polish", native: "Polski", rtl: false },
  nl: { name: "Dutch", native: "Nederlands", rtl: false },
  th: { name: "Thai", native: "ไทย", rtl: false },
  id: { name: "Indonesian", native: "Bahasa Indonesia", rtl: false },
  ms: { name: "Malay", native: "Bahasa Melayu", rtl: false },
  fa: { name: "Persian", native: "فارسی", rtl: true },
  ur: { name: "Urdu", native: "اردو", rtl: true },
  ta: { name: "Tamil", native: "தமிழ்", rtl: false },
  te: { name: "Telugu", native: "తెలుగు", rtl: false },
  mr: { name: "Marathi", native: "मराठी", rtl: false },
  gu: { name: "Gujarati", native: "ગુજરાતી", rtl: false },
  kn: { name: "Kannada", native: "ಕನ್ನಡ", rtl: false },
  ml: { name: "Malayalam", native: "മലയാളം", rtl: false },
  bn: { name: "Bengali", native: "বাংলা", rtl: false },
  pa: { name: "Punjabi", native: "ਪੰਜਾਬੀ", rtl: false },
  sw: { name: "Swahili", native: "Kiswahili", rtl: false },
  am: { name: "Amharic", native: "አማርኛ", rtl: false },
  ha: { name: "Hausa", native: "Hausa", rtl: false },
  yo: { name: "Yoruba", native: "Yorùbá", rtl: false },
  he: { name: "Hebrew", native: "עברית", rtl: true },
  ro: { name: "Romanian", native: "Română", rtl: false },
  cs: { name: "Czech", native: "Čeština", rtl: false },
  sv: { name: "Swedish", native: "Svenska", rtl: false },
  no: { name: "Norwegian", native: "Norsk", rtl: false },
  da: { name: "Danish", native: "Dansk", rtl: false },
  fi: { name: "Finnish", native: "Suomi", rtl: false },
  el: { name: "Greek", native: "Ελληνικά", rtl: false },
  hu: { name: "Hungarian", native: "Magyar", rtl: false },
  bg: { name: "Bulgarian", native: "Български", rtl: false },
  sr: { name: "Serbian", native: "Српски", rtl: false },
  hr: { name: "Croatian", native: "Hrvatski", rtl: false },
  sk: { name: "Slovak", native: "Slovenčina", rtl: false },
  sl: { name: "Slovenian", native: "Slovenščina", rtl: false },
  lt: { name: "Lithuanian", native: "Lietuvių", rtl: false },
  lv: { name: "Latvian", native: "Latviešu", rtl: false },
  et: { name: "Estonian", native: "Eesti", rtl: false },
  sq: { name: "Albanian", native: "Shqip", rtl: false },
  mk: { name: "Macedonian", native: "Македонски", rtl: false },
  bs: { name: "Bosnian", native: "Bosanski", rtl: false },
  be: { name: "Belarusian", native: "Беларуская", rtl: false },
  ka: { name: "Georgian", native: "ქართული", rtl: false },
  hy: { name: "Armenian", native: "Հայերեն", rtl: false },
  az: { name: "Azerbaijani", native: "Azərbaycan", rtl: false },
  kk: { name: "Kazakh", native: "Қазақша", rtl: false },
  uz: { name: "Uzbek", native: "Oʻzbekcha", rtl: false },
  ky: { name: "Kyrgyz", native: "Кыргызча", rtl: false },
  tg: { name: "Tajik", native: "Тоҷикӣ", rtl: false },
  mn: { name: "Mongolian", native: "Монгол", rtl: false },
  ne: { name: "Nepali", native: "नेपाली", rtl: false },
  si: { name: "Sinhala", native: "සිංහල", rtl: false },
  my: { name: "Burmese", native: "မြန်မာ", rtl: false },
  km: { name: "Khmer", native: "ខ្មែរ", rtl: false },
  lo: { name: "Lao", native: "ລາວ", rtl: false },
  tl: { name: "Filipino", native: "Filipino", rtl: false },
  jv: { name: "Javanese", native: "Basa Jawa", rtl: false },
  su: { name: "Sundanese", native: "Basa Sunda", rtl: false },
  ceb: { name: "Cebuano", native: "Cebuano", rtl: false },
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { LANGUAGES };
}
if (typeof window !== "undefined") {
  window.LANGUAGES = LANGUAGES;
}
